baseURL = 'https://cld4h.github.io/LARBS'
languageCode = 'en-us'
title = 'LARBS'

theme = 'lugo'

[params]
  taglist = false
  nextprev = false
  datesinlist = false
  authorsinlist = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
